import { FieldSchema } from "./type";

export const headOfFamilyPersonalInfoSchema : FieldSchema[] = [
    {
        name: 'hofname',
        label: 'Name',
        placeholder: "Head of Family's Name",
        type: 'text',
        required: true,
    },
    {
        name: 'hofMembershipNumber',
        label: 'Membership Number',
        placeholder: "Head of Family's Membership Number",
        type: 'text',
        required: true,
    },
    {
        name: 'hofMembershipType',
        label: 'Membership Type',
        type: 'select',
        options: ['Lifetime', 'Regular'],
        required: true,
    },
    {
        name: 'hofDob',
        label: 'Date of Birth',
        type: 'date',
        required: true,
    },
    {
        name: 'hofGender',
        label: 'Gender',
        type: 'select',
        options: ['Male', 'Female'],
        required: true,
    },
    {
        name: 'hofEmail',
        label: 'Email',
        placeholder: "Head of Family's Email",
        type: 'email',
        required: true,
    },
    {
        name: 'hofMobile',
        label: 'Mobile',
        placeholder: "Head of Family's Primary Mobile",
        type: 'phone',
        required: true,
    },
    {
        name: 'hofSecondMobile',
        label: 'Second Mobile',
        placeholder: "Head of Family's Secondary Mobile",
        type: 'phone',
        required: false,
    },
    {
        name: 'hofAddressStreet',
        label: 'Address Street',
        placeholder: "House Number, Street Name",
        type: 'text',
        required: true,
    },
    {
        name: 'hofAddressCity',
        label: 'Address City',
        placeholder: "City",
        type: 'text',
        required: true,
    },
    {
        name: 'hofAddressState',
        label: 'Address State',
        placeholder: "State",
        type: 'text',
        required: true,
    },
    {
        name: 'hofAddressPostalCode',
        label: 'Address Postal Code',
        placeholder: "Postal Code",
        type: 'text',
        required: true,
    },
    {
        name: 'hofPhoto',
        label: 'Photo',
        type: 'file',
        required: true,
    },
    {
        name: 'hofBloodGroup',
        label: 'Blood Group',
        type: 'select',
        options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Others'],
        required: true,
    },
    {
        name: 'hofIsBloodDonor',
        label: 'Is Blood Donor',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
    },
    {
        name: 'hofMaritalStatus',
        label: 'Marital Status',
        type: 'select',
        options: ['Single', 'Married - Outside Samaj', 'Married - Within Samaj', 'Divorced - Outside Samaj', 'Divorced - Within Samaj', 'Widowed - Outside Samaj', 'Widowed - Within Samaj'],
        required: true,
    },
    {
        name: 'hofCountryOfResidence',
        label: 'Country of Residence',
        type: 'select',
        options: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Anguilla", "Antigua &amp; Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia &amp; Herzegovina", "Botswana", "Brazil", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Cape Verde", "Cayman Islands", "Chad", "Chile", "China", "Colombia", "Congo", "Cook Islands", "Costa Rica", "Cote D Ivoire", "Croatia", "Cruise Ship", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Estonia", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Polynesia", "French West Indies", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kuwait", "Kyrgyz Republic", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Namibia", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russia", "Rwanda", "Saint Pierre &amp; Miquelon", "Samoa", "San Marino", "Satellite", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "South Africa", "South Korea", "Spain", "Sri Lanka", "St Kitts &amp; Nevis", "St Lucia", "St Vincent", "St. Lucia", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor L'Este", "Togo", "Tonga", "Trinidad &amp; Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks &amp; Caicos", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Venezuela", "Vietnam", "Virgin Islands (US)", "Yemen", "Zambia", "Zimbabwe"],
        required: true,
    },
    {
        name: 'hofExtraNotes',
        label: 'Extra Notes',
        type: 'textarea',
        placeholder: "If some other information is required, please mention it here",
        required: false,
    }
]